### ISSUE TITLE
Capability to calculate the time when the maximum water elevation occurs

### ISSUE THREAD

**Issue by pvelissariou1** [schism-dev/schism#189]
It is desirable in storm surge modeling to know the time when the maximum water elevation occurs (using both internal calculations & post-processing calculations using the ouput files).

**Comment by pvelissariou1** [comment]
@josephzhang8 Yes, Joseph. What exactly you want me to do? I am already using read_output10_allnodes in my evaluation scripts. Do I need to update my schism code?

**Comment by pvelissariou1** [comment]
Actually I am using read_output8_allnodes for the shoout* files, read_output10_allnodes for the out2d* files and combine_gr3 to combine the maxelev_[0-9]* files. I'll pull the code and use it in one of my test cases (I believe, I will update you by tomorrow). Thank you for such a quick response.

**Comment by josephzhang8** [comment]
Thx Takis. I've also added it into read_output8_allnodes in the latest master.

**Comment by pvelissariou1** [comment]
In both `read_output10_allnodes.f90` and `read_output8_allnodes.f90` I modified the '`open(12, ...` statement to:
open(12,file=trim(adjustl(varname))//'_'//trim(adjustl(outname(k)))//'.gr3'**,recl=512**,status='replace')
otherwise, the times are written in the next line.
As an input to `read_output10_allnodes.f90` I am using:
```
elevation  ! variable name
1          ! switch for variable type: scalar (1) or vector (2)?
1 1        ! start and end stacks; out2d_1.nc, out2d_2.nc, ...
0 1 1      ! switches for min, max, avg; compute stats for 2D var (0/1:min; 0/1:max; 0/1:time avg)
-999999    ! threshold for outputing violators.bp, where violaters are nodes/eles with var values < 
1          ! initialization flag: (0) do nothing;  (1) intialized to -dp (useful for maxelev)
```
I am checking with 6min outputs and will be plotting the results for TC Helene.

**Comment by pvelissariou1** [comment]
I'll revert back to formatted output. I am working on a pull request to include combining outputs/maxelev_* and outputs/maxdahv_* files that also include the times at max* values.

**Comment by josephzhang8** [comment]
> In both `read_output10_allnodes.f90` and `read_output8_allnodes.f90` I modified the '`open(12, ...` statement to: open(12,file=trim(adjustl(varname))//'_'//trim(adjustl(outname(k)))//'.gr3'**,recl=512**,status='replace') otherwise, the times are written in the next line. As an input to `read_output10_allnodes.f90` I am using:
> 
> ```
> elevation  ! variable name
> 1          ! switch for variable type: scalar (1) or vector (2)?
> 1 1        ! start and end stacks; out2d_1.nc, out2d_2.nc, ...
> 0 1 1      ! switches for min, max, avg; compute stats for 2D var (0/1:min; 0/1:max; 0/1:time avg)
> -999999    ! threshold for outputing violators.bp, where violaters are nodes/eles with var values < 
> 1          ! initialization flag: (0) do nothing;  (1) intialized to -dp (useful for maxelev)
> ```
> 
> I am checking with 6min outputs and will be plotting the results for TC Helene.

Why do you need recl=512?

**Comment by pvelissariou1** [comment]
i had to use the RECL specifier, otherwise the times were written to the next line, instead in the same line with the max. elevation (for unformatted output there is a line length limit of 72 characters I believe. The 512 number is arbitrary.  I'll go to formatted output instead. I'll submit a pull request later today with my changes.

**Comment by josephzhang8** [comment]
Thx. Formatted outputs are the good option.

**Comment by josephzhang8** [comment]
Thx Takis. Please see my reviews.

**Comment by pvelissariou1** [comment]
Done, Added the links. Please review

Panagiotis Velissariou, Ph.D., P.E.
Assoc. Scientist III
UCAR/CPAESS at NOAA, National Hurricane Center
National Weather Service
National Ocean and Atmospheric Administration
cell: (205) 227-9141
email: ***@***.***

**Comment by josephzhang8** [comment]
Thx Takis. I still see a lot of deleted files in the PR 190.


[cid:da5fd160-6a25-4255-ae27-9f9dce59d251]




-Joseph



Joseph Zhang

Office: (804) 684 7466

Web: schism.wiki



________________________________
